package com.zoro.zoromart.dao;
import java.sql.*;import java.math.BigDecimal;import java.util.*;
/** JDBC operations for carts, orders, reviews and admin views. */
public class MarketplaceDAO {private final Connection c;public MarketplaceDAO(Connection c){this.c=c;}
 public List<Map<String,Object>> cart(long user)throws SQLException{String s="SELECT ci.id,ci.product_id,ci.quantity,p.name,p.price,p.stock_qty,p.image_url,(p.price*ci.quantity) lineTotal FROM cart_items ci JOIN products p ON p.id=ci.product_id WHERE ci.user_id=? ORDER BY ci.id";try(PreparedStatement p=c.prepareStatement(s)){p.setLong(1,user);try(ResultSet r=p.executeQuery()){List<Map<String,Object>> a=new ArrayList<>();while(r.next()){Map<String,Object> m=new LinkedHashMap<>();m.put("id",r.getLong(1));m.put("productId",r.getLong(2));m.put("quantity",r.getInt(3));m.put("name",r.getString(4));m.put("price",r.getBigDecimal(5));m.put("stockQty",r.getInt(6));m.put("imageUrl",r.getString(7));m.put("lineTotal",r.getBigDecimal(8));a.add(m);}return a;}}}
 public void addCart(long user,long product,int qty)throws SQLException{try(PreparedStatement p=c.prepareStatement("UPDATE cart_items SET quantity=quantity+? WHERE user_id=? AND product_id=?")){p.setInt(1,qty);p.setLong(2,user);p.setLong(3,product);if(p.executeUpdate()==0){try(PreparedStatement i=c.prepareStatement("INSERT INTO cart_items(user_id,product_id,quantity) VALUES(?,?,?)")){i.setLong(1,user);i.setLong(2,product);i.setInt(3,qty);i.executeUpdate();}}}}
 public boolean updateCart(long user,long id,int qty)throws SQLException{try(PreparedStatement p=c.prepareStatement("UPDATE cart_items SET quantity=? WHERE id=? AND user_id=? AND ? <= (SELECT stock_qty FROM products WHERE id=cart_items.product_id)")){p.setInt(1,qty);p.setLong(2,id);p.setLong(3,user);p.setInt(4,qty);return p.executeUpdate()>0;}}
 public boolean removeCart(long user,long id)throws SQLException{try(PreparedStatement p=c.prepareStatement("DELETE FROM cart_items WHERE id=? AND user_id=?")){p.setLong(1,id);p.setLong(2,user);return p.executeUpdate()>0;}}
 public long checkout(long user)throws SQLException{boolean old=c.getAutoCommit();c.setAutoCommit(false);try{List<Map<String,Object>> items=cart(user);if(items.isEmpty())throw new IllegalArgumentException("Cart is empty");BigDecimal total=BigDecimal.ZERO;for(Map<String,Object> i:items){int q=((Number)i.get("quantity")).intValue(),stock=((Number)i.get("stockQty")).intValue();if(q>stock)throw new IllegalArgumentException("Insufficient stock for "+i.get("name"));total=total.add((BigDecimal)i.get("lineTotal"));}long order;try(PreparedStatement p=c.prepareStatement("INSERT INTO orders(buyer_id,status,total_amount) VALUES(?,?,?)",Statement.RETURN_GENERATED_KEYS)){p.setLong(1,user);p.setString(2,"CONFIRMED");p.setBigDecimal(3,total);p.executeUpdate();try(ResultSet r=p.getGeneratedKeys()){r.next();order=r.getLong(1);}}for(Map<String,Object> i:items){long pid=((Number)i.get("productId")).longValue();int q=((Number)i.get("quantity")).intValue();try(PreparedStatement p=c.prepareStatement("INSERT INTO order_items(order_id,product_id,quantity,unit_price) SELECT ?,id,?,price FROM products WHERE id=?")){p.setLong(1,order);p.setInt(2,q);p.setLong(3,pid);p.executeUpdate();}try(PreparedStatement p=c.prepareStatement("UPDATE products SET stock_qty=stock_qty-? WHERE id=? AND stock_qty>=?")){p.setInt(1,q);p.setLong(2,pid);p.setInt(3,q);if(p.executeUpdate()!=1)throw new IllegalArgumentException("Stock changed. Please retry checkout.");}}try(PreparedStatement p=c.prepareStatement("DELETE FROM cart_items WHERE user_id=?")){p.setLong(1,user);p.executeUpdate();}c.commit();return order;}catch(Exception e){c.rollback();if(e instanceof SQLException se)throw se;if(e instanceof RuntimeException re)throw re;throw new SQLException(e);}finally{c.setAutoCommit(old);}}
 public List<Map<String,Object>> orders(long user,boolean admin)throws SQLException{String sql="SELECT o.id,o.buyer_id,u.name buyer_name,o.status,o.total_amount,o.created_at FROM orders o JOIN users u ON u.id=o.buyer_id "+(admin?"":"WHERE o.buyer_id=? ")+"ORDER BY o.created_at DESC";try(PreparedStatement p=c.prepareStatement(sql)){if(!admin)p.setLong(1,user);try(ResultSet r=p.executeQuery()){List<Map<String,Object>> a=new ArrayList<>();while(r.next()){Map<String,Object> m=new LinkedHashMap<>();m.put("id",r.getLong(1));m.put("buyerId",r.getLong(2));m.put("buyerName",r.getString(3));m.put("status",r.getString(4));m.put("totalAmount",r.getBigDecimal(5));m.put("createdAt",r.getTimestamp(6).toString());a.add(m);}return a;}}}
 public List<Map<String,Object>> orderItems(long orderId,long buyer)throws SQLException{String sql="SELECT oi.product_id,p.name,oi.quantity,oi.unit_price FROM order_items oi JOIN orders o ON o.id=oi.order_id JOIN products p ON p.id=oi.product_id WHERE o.id=? AND o.buyer_id=? ORDER BY oi.id";try(PreparedStatement p=c.prepareStatement(sql)){p.setLong(1,orderId);p.setLong(2,buyer);try(ResultSet r=p.executeQuery()){List<Map<String,Object>> a=new ArrayList<>();while(r.next()){Map<String,Object> m=new LinkedHashMap<>();m.put("productId",r.getLong(1));m.put("name",r.getString(2));m.put("quantity",r.getInt(3));m.put("unitPrice",r.getBigDecimal(4));a.add(m);}return a;}}}
 public List<Map<String,Object>> sellerOrders(long seller)throws SQLException{String sql="SELECT DISTINCT o.id,o.buyer_id,u.name buyer_name,o.status,o.total_amount,o.created_at FROM orders o JOIN users u ON u.id=o.buyer_id JOIN order_items oi ON oi.order_id=o.id JOIN products p ON p.id=oi.product_id WHERE p.seller_id=? ORDER BY o.created_at DESC";try(PreparedStatement p=c.prepareStatement(sql)){p.setLong(1,seller);try(ResultSet r=p.executeQuery()){List<Map<String,Object>> a=new ArrayList<>();while(r.next()){Map<String,Object> m=new LinkedHashMap<>();m.put("id",r.getLong(1));m.put("buyerId",r.getLong(2));m.put("buyerName",r.getString(3));m.put("status",r.getString(4));m.put("totalAmount",r.getBigDecimal(5));m.put("createdAt",r.getTimestamp(6).toString());a.add(m);}return a;}}}
 public void review(long user,long order,long product,int rating,String comment)throws SQLException{try(PreparedStatement p=c.prepareStatement("INSERT INTO reviews(product_id,user_id,order_id,rating,comment) SELECT ?,?,?,?,? WHERE EXISTS(SELECT 1 FROM orders o JOIN order_items i ON i.order_id=o.id WHERE o.id=? AND o.buyer_id=? AND o.status='DELIVERED' AND i.product_id=?)")){p.setLong(1,product);p.setLong(2,user);p.setLong(3,order);p.setInt(4,rating);p.setString(5,comment);p.setLong(6,order);p.setLong(7,user);p.setLong(8,product);if(p.executeUpdate()!=1)throw new IllegalArgumentException("Review requires your completed order containing this product");}}
 public List<Map<String,Object>> reviews(long product)throws SQLException{try(PreparedStatement p=c.prepareStatement("SELECT r.rating,r.comment,r.created_at,u.name FROM reviews r JOIN users u ON u.id=r.user_id WHERE r.product_id=? ORDER BY r.created_at DESC")){p.setLong(1,product);try(ResultSet r=p.executeQuery()){List<Map<String,Object>> a=new ArrayList<>();while(r.next()){Map<String,Object> m=new LinkedHashMap<>();m.put("rating",r.getInt(1));m.put("comment",r.getString(2));m.put("createdAt",r.getTimestamp(3).toString());m.put("reviewer",r.getString(4));a.add(m);}return a;}}}
 public boolean updateStatus(long id,String status)throws SQLException{try(PreparedStatement p=c.prepareStatement("UPDATE orders SET status=? WHERE id=?")){p.setString(1,status);p.setLong(2,id);return p.executeUpdate()>0;}}
}
