package com.zoro.zoromart.controller;

import com.google.gson.JsonObject;import com.google.gson.JsonParser;import com.google.gson.JsonParseException;import com.zoro.zoromart.dao.*;import com.zoro.zoromart.service.*;import com.zoro.zoromart.util.*;import org.slf4j.Logger;import org.slf4j.LoggerFactory;
import javax.servlet.annotation.WebServlet;import javax.servlet.http.*;import javax.servlet.ServletException;import java.io.*;import java.math.BigDecimal;import java.sql.*;import java.util.*;
/** Versioned API front controller. HTTP orchestration only; SQL is isolated in DAO classes. */
@WebServlet(urlPatterns="/api/v1/*")
public class ApiServlet extends HttpServlet {private static final Logger log=LoggerFactory.getLogger(ApiServlet.class);
 private JsonObject readBody(HttpServletRequest r)throws IOException{String s=r.getReader().lines().reduce("",(a,b)->a+b);return s.isBlank()?new JsonObject():JsonParser.parseString(s).getAsJsonObject();}
 private String str(JsonObject b,String k){return b.has(k)&&!b.get(k).isJsonNull()?b.get(k).getAsString():null;}private long num(JsonObject b,String k){if(!b.has(k)||b.get(k).isJsonNull())throw new IllegalArgumentException(k+" is required");try{return b.get(k).getAsLong();}catch(RuntimeException e){throw new IllegalArgumentException(k+" must be a number");}}private int integer(JsonObject b,String k){if(!b.has(k)||b.get(k).isJsonNull())throw new IllegalArgumentException(k+" is required");try{return b.get(k).getAsInt();}catch(RuntimeException e){throw new IllegalArgumentException(k+" must be a number");}}private long uid(HttpServletRequest r){Object x=r.getSession(false)==null?null:r.getSession(false).getAttribute("userId");return x instanceof Number n?n.longValue():-1;}private String role(HttpServletRequest r){Object x=r.getSession(false)==null?null:r.getSession(false).getAttribute("role");return x==null?"":x.toString();}private void requireRole(HttpServletRequest req,HttpServletResponse res,String... roles)throws IOException{if(uid(req)<0){JsonUtil.write(res,401,JsonUtil.error("UNAUTHENTICATED","Please log in"));throw new StopRequest();}if(Arrays.stream(roles).noneMatch(x->x.equals(role(req)))){JsonUtil.write(res,403,JsonUtil.error("FORBIDDEN","Your account role cannot perform this action"));throw new StopRequest();}}private static class StopRequest extends RuntimeException{}
 @Override protected void doGet(HttpServletRequest req,HttpServletResponse res)throws IOException{handle(req,res,"GET");}@Override protected void doPost(HttpServletRequest req,HttpServletResponse res)throws IOException{handle(req,res,"POST");}@Override protected void doPut(HttpServletRequest req,HttpServletResponse res)throws IOException{handle(req,res,"PUT");}@Override protected void doDelete(HttpServletRequest req,HttpServletResponse res)throws IOException{handle(req,res,"DELETE");}
 private void handle(HttpServletRequest req,HttpServletResponse res,String method)throws IOException{String path=req.getPathInfo()==null?"/":req.getPathInfo();try(Connection c=Db.connection(getServletContext())){JsonObject b=(method.equals("GET")||method.equals("DELETE"))?new JsonObject():readBody(req);Object data;
 if(path.equals("/health")&&method.equals("GET")){try(PreparedStatement p=c.prepareStatement("SELECT 1");ResultSet rs=p.executeQuery()){rs.next();}data=Map.of("status","UP","db","UP");JsonUtil.write(res,200,JsonUtil.ok(data));return;}
 if(path.equals("/auth/register")&&method.equals("POST")){String role=str(b,"role");if("ADMIN".equalsIgnoreCase(role)){JsonUtil.write(res,400,JsonUtil.error("VALIDATION_ERROR","Admin registration is disabled"));return;}data=new AuthService(new UserDAO(c)).register(str(b,"name"),str(b,"email"),str(b,"password"),role);JsonUtil.write(res,201,JsonUtil.ok(data));return;}
 if(path.equals("/auth/login")&&method.equals("POST")){Map<String,Object> u=new AuthService(new UserDAO(c)).login(str(b,"email"),str(b,"password"));if(u==null){JsonUtil.write(res,401,JsonUtil.error("INVALID_CREDENTIALS","Email or password is incorrect"));return;}HttpSession old=req.getSession(false);if(old!=null)old.invalidate();HttpSession s=req.getSession(true);s.setMaxInactiveInterval(1800);s.setAttribute("userId",u.get("id"));s.setAttribute("role",u.get("role"));s.setAttribute("name",u.get("name"));JsonUtil.write(res,200,JsonUtil.ok(u));return;}
 if(path.equals("/auth/logout")&&method.equals("POST")){HttpSession s=req.getSession(false);if(s!=null)s.invalidate();JsonUtil.write(res,200,JsonUtil.ok(Map.of("message","Logged out")));return;}
 if(path.equals("/auth/me")&&method.equals("GET")){if(uid(req)<0){JsonUtil.write(res,401,JsonUtil.error("UNAUTHENTICATED","Please log in"));return;}data=Map.of("id",uid(req),"name",String.valueOf(req.getSession().getAttribute("name")),"role",role(req));JsonUtil.write(res,200,JsonUtil.ok(data));return;}
 if(path.equals("/products")&&method.equals("GET")){data=new ProductService(new ProductDAO(c)).search(req.getParameter("q"),req.getParameter("category"));JsonUtil.write(res,200,JsonUtil.ok(data));return;}
 if(path.matches("/products/\\d+/reviews")&&method.equals("GET")){long id=Long.parseLong(path.split("/")[2]);data=new MarketplaceDAO(c).reviews(id);JsonUtil.write(res,200,JsonUtil.ok(data));return;}
 if(path.equals("/products")&&method.equals("POST")){requireRole(req,res,"SELLER");String name=str(b,"name"),desc=str(b,"description"),cat=str(b,"category");int stock=integer(b,"stockQty");long id=new ProductService(new ProductDAO(c)).create(uid(req),name,desc,str(b,"price"),stock,cat,str(b,"imageUrl"));JsonUtil.write(res,201,JsonUtil.ok(Map.of("id",id)));return;}
 if(path.matches("/products/\\d+")&&method.equals("PUT")){requireRole(req,res,"SELLER");long id=Long.parseLong(path.substring(10));boolean ok=new ProductService(new ProductDAO(c)).update(id,uid(req),str(b,"name"),str(b,"description"),str(b,"price"),integer(b,"stockQty"),str(b,"category"),str(b,"imageUrl"));if(!ok){JsonUtil.write(res,404,JsonUtil.error("NOT_FOUND","Listing not found or not owned by this seller"));return;}JsonUtil.write(res,200,JsonUtil.ok(Map.of("updated",true)));return;}
 if(path.matches("/products/\\d+")&&method.equals("DELETE")){requireRole(req,res,"SELLER","ADMIN");long id=Long.parseLong(path.substring(10));boolean admin="ADMIN".equals(role(req));if(!new ProductService(new ProductDAO(c)).delete(id,uid(req),admin)){JsonUtil.write(res,404,JsonUtil.error("NOT_FOUND","Listing not found"));return;}JsonUtil.write(res,200,JsonUtil.ok(Map.of("deleted",true)));return;}
 if(path.equals("/seller/products")&&method.equals("GET")){requireRole(req,res,"SELLER");JsonUtil.write(res,200,JsonUtil.ok(new ProductService(new ProductDAO(c)).ownListings(uid(req))));return;}
 if(path.equals("/cart/items")&&method.equals("GET")){requireRole(req,res,"BUYER");data=new CartService(new MarketplaceDAO(c),new ProductDAO(c)).get(uid(req));JsonUtil.write(res,200,JsonUtil.ok(data));return;}
 if(path.equals("/cart/items")&&method.equals("POST")){requireRole(req,res,"BUYER");long pid=num(b,"productId");new CartService(new MarketplaceDAO(c),new ProductDAO(c)).add(uid(req),pid,integer(b,"quantity"));JsonUtil.write(res,201,JsonUtil.ok(Map.of("added",true)));return;}
 if(path.matches("/cart/items/\\d+")&&method.equals("PUT")){requireRole(req,res,"BUYER");if(!new CartService(new MarketplaceDAO(c),new ProductDAO(c)).update(uid(req),Long.parseLong(path.substring(12)),integer(b,"quantity"))){JsonUtil.write(res,404,JsonUtil.error("NOT_FOUND","Cart item not found"));return;}JsonUtil.write(res,200,JsonUtil.ok(Map.of("updated",true)));return;}
 if(path.matches("/cart/items/\\d+")&&method.equals("DELETE")){requireRole(req,res,"BUYER");if(!new CartService(new MarketplaceDAO(c),new ProductDAO(c)).remove(uid(req),Long.parseLong(path.substring(12)))){JsonUtil.write(res,404,JsonUtil.error("NOT_FOUND","Cart item not found"));return;}JsonUtil.write(res,200,JsonUtil.ok(Map.of("removed",true)));return;}
 if(path.matches("/orders/\\d+/items")&&method.equals("GET")){requireRole(req,res,"BUYER");long oid=Long.parseLong(path.split("/")[2]);JsonUtil.write(res,200,JsonUtil.ok(new MarketplaceDAO(c).orderItems(oid,uid(req))));return;}
 if(path.equals("/orders")&&method.equals("POST")){requireRole(req,res,"BUYER");Object order=new OrderService(PaymentStrategyFactory.create()).checkout(new MarketplaceDAO(c),uid(req));JsonUtil.write(res,201,JsonUtil.ok(order));return;}
 if(path.equals("/orders")&&method.equals("GET")){requireRole(req,res,"BUYER","ADMIN");JsonUtil.write(res,200,JsonUtil.ok(new MarketplaceDAO(c).orders(uid(req),"ADMIN".equals(role(req)))));return;}
 if(path.equals("/seller/orders")&&method.equals("GET")){requireRole(req,res,"SELLER");JsonUtil.write(res,200,JsonUtil.ok(new MarketplaceDAO(c).sellerOrders(uid(req))));return;}
 if(path.equals("/reviews")&&method.equals("POST")){requireRole(req,res,"BUYER");int rating=integer(b,"rating");if(rating<1||rating>5)throw new IllegalArgumentException("Rating must be 1–5");new MarketplaceDAO(c).review(uid(req),num(b,"orderId"),num(b,"productId"),rating,str(b,"comment"));JsonUtil.write(res,201,JsonUtil.ok(Map.of("created",true)));return;}
 if(path.equals("/admin/users")&&method.equals("GET")){requireRole(req,res,"ADMIN");JsonUtil.write(res,200,JsonUtil.ok(new UserDAO(c).all()));return;}
 if(path.equals("/admin/orders")&&method.equals("GET")){requireRole(req,res,"ADMIN");JsonUtil.write(res,200,JsonUtil.ok(new MarketplaceDAO(c).orders(uid(req),true)));return;}
 if(path.matches("/admin/orders/\\d+/status")&&method.equals("PUT")){requireRole(req,res,"ADMIN");String st=ValidationUtil.required(str(b,"status"),"status").toUpperCase(Locale.ROOT);if(!Set.of("PENDING","CONFIRMED","SHIPPED","DELIVERED","CANCELLED").contains(st))throw new IllegalArgumentException("Invalid order status");if(!new MarketplaceDAO(c).updateStatus(Long.parseLong(path.split("/")[3]),st)){JsonUtil.write(res,404,JsonUtil.error("NOT_FOUND","Order not found"));return;}JsonUtil.write(res,200,JsonUtil.ok(Map.of("updated",true)));return;}
 if(path.equals("/chat")&&method.equals("POST")){HttpSession s=req.getSession(true);String msg=str(b,"message");data=Map.of("reply",((ChatService)getServletContext().getAttribute("chatService")).reply(s.getId(),msg));JsonUtil.write(res,200,JsonUtil.ok(data));return;}
 JsonUtil.write(res,404,JsonUtil.error("NOT_FOUND","API route not found"));
 }catch(StopRequest ignored){}catch(JsonParseException e){try{JsonUtil.write(res,400,JsonUtil.error("VALIDATION_ERROR","Request body must be valid JSON"));}catch(IOException ignored){}}catch(IllegalArgumentException e){try{JsonUtil.write(res,400,JsonUtil.error("VALIDATION_ERROR",e.getMessage()));}catch(IOException ignored){}}catch(SQLException e){log.error("Database/API error",e);try{if("23505".equals(e.getSQLState())||"23503".equals(e.getSQLState()))JsonUtil.write(res,409,JsonUtil.error("CONFLICT","The request conflicts with existing data"));else JsonUtil.write(res,500,JsonUtil.error("SERVER_ERROR","Request could not be completed"));}catch(IOException ignored){}}catch(Exception e){log.error("Unexpected API error",e);try{JsonUtil.write(res,500,JsonUtil.error("SERVER_ERROR","Request could not be completed"));}catch(IOException ignored){}}}
}
